### ISSUE TITLE
Getting push notifications but nothing is showing in the app

### ISSUE THREAD

**Issue by yaakovgamliel** [RuiAAPeres/OctifyIssues#4]

**Comment by yaakovgamliel** [comment]
I'm currently receiving push notifications but the apps doesn't show any either the website, let me know what you think

**Comment by RuiAAPeres** [comment]
@yaakovgamliel so sorry for only seeing this now. Have you been able to reproduce this on the latest build?

**Comment by yaakovgamliel** [comment]
I stopped using the app, but I'll check out the latest build.
Thanks for your time.

**Comment by RuiAAPeres** [comment]
@yaakovgamliel is there any feature you would like to see there, in order for you to use it again?

**Comment by yaakovgamliel** [comment]
I just installed the app again to test the notifications issue, it would be very could if you could add 1Password support .
Thanks again for your time

**Comment by yaakovgamliel** [comment]
The app is not showing in Settings -> Notofications, and I wasn't prompt to aloud notifications, this is the first time I install the app in this phone (iPhone 6, running 8.1).
Again thanks for your time and btw I'm writing here only to help not trying to be annoying :)

**Comment by RuiAAPeres** [comment]
@yaakovgamliel all the feedback is very much welcome and it's the only way to push the product forward. :+1: 

Right now the app uses Background Notifications and not Push Notifications so you don't need to give permissions to that. The 1Password support is something I will look into!

**Comment by yaakovgamliel** [comment]
Great looking forward for it!

**Comment by RuiAAPeres** [comment]
So I will close this issue @yaakovgamliel but please feel free to open a new one if needed.
